### PR TITLE
fix: `useTrackRenders` should be usable inside of wrappers

### LINKED ISSUE #7: Cannot use `useTrackRenders` when component is used in the `wrapper` option
When using `renderStream.render`, I am unable to to use components that use the `useTrackRenders` hook in the `wrapper` option. As an example, see [this test](https://github.com/apollographql/apollo-client/blob/60b99d119c44a9223ef3adfabd32e23c9ca73f03/src/react/hooks/__tests__/useSuspenseQuery.test.tsx#L10649-L10660) from an Apollo Client bug that I'm working on. I'd like to move the `<Suspense />` and `<ErrorBoundary />` components to the `wrapper` option. When doing so however, I see the error:

```
useTrackRenders: A Render Stream must be created and rendered to track component renders
```

Ideally `useTrackRenders` can be used for components in the components passed to `render` and `wrapper`. This would also make it easier for more of these complex cases to use `rerender` to avoid the need to pass that whole component tree again.

### PR DESCRIPTION
**Pull request by phryneas**
This swaps the `ParentWrapper` and `Wrapper` components in the `render` function call, so that calls that require context (e.g. `useTrackRenders`) can also be used in user-supplied `wrapper` options.

Fixes #7

### CODE REVIEW

**Comment by phryneas** [comment]
@jerelmiller all that said, I want to take a step back: do we really want to do this?

Especially if we add "auto-injection" of `useTrackRender` into play in the future, this would e.g. capture the `ApolloProvider` as a "rerendered component" - which might be less than desirable. Also, you might not want to track each rerender of components in `Wrapper` that doesn't affect the children.

This might actually kinda take a feature away, not fix one.

**Comment by jerelmiller** [comment]
That's fair. I think I'm stuck thinking in terms of our old implementation, but your reasons for not wanting to go this route make sense.

**Review by jerelmiller — APPROVED** [review]
I trust your judgement on whether you want to actually introduce this or not but here's an approval either way 🙂

**Comment by phryneas** [comment]
I think let's close it for now. If we get a lot of feedback in this direction, we can still pick it up, or introduce something like an `InnerWrapper` option.

**Pull request closed without merging**
